var express = require('express');
var router = express.Router();

const glossary = [
  {
    Number:'1',
    term: 'Apache',
    definition: ' one of the most well-known open-source web servers is a robust cross-platform utility that allows for the easy and flexible deployment of websites and apps.',
    sources: 'Anon, (2018). DevOps glossary: 78 basic DevOps terms explained in simple words | IT Svit. [online] Available at: https://itsvit.com/blog/devops-glossary-78-basic-devops-terms-in-simple-words/ [Accessed 13 Jul. 2023].'},
    {Number:'2',
      term: 'Bucket',
    definition: 'An S3 bucket, which is similar to a virtual storage container in Amazon S3 (Simple Storage Service), is where you can keep various types of files and the information associated with them."',
    sources: 'Anon, (2018). DevOps glossary: 78 basic DevOps terms explained in simple words | IT Svit. [online] Available at: https://itsvit.com/blog/devops-glossary-78-basic-devops-terms-in-simple-words/ [Accessed 13 Jul. 2023].',
  },
  {
    Number:'3',
    term: 'Artifact',
  definition: 'In the context of a project, an artefact is any documentation or deliverable that is critical in defining the functionality, architecture, and design features of the software being developed.',
  sources: 'Plutora. (n.d.). DevOps DevOps Terminology: A Glossary. [online] Available at: https://www.plutora.com/devops-at-scale/terminology-glossary.'},
  {Number:'4',
    term: 'Capacity Test',
  definition: 'Capacity tests evaluate an applications ability to handle a given number of users or transactions, providing a system performance baseline. This type of test helps us to assess the applications limits and establish its ability to handle a large workload.',
  sources: 'Plutora. (n.d.). DevOps DevOps Terminology: A Glossary. [online] Available at: https://www.plutora.com/devops-at-scale/terminology-glossary.'},
  {Number:'5',
    term: 'Deployment',
  definition: 'There comes a point in the software delivery process when we carefully package the new code, distribute it to our valued clients, and seamlessly update the operating applications, all while assuring a smooth user experience with no interruptions.',
  sources: 'Anon, (2018). DevOps glossary: 78 basic DevOps terms explained in simple words | IT Svit. [online] Available at: https://itsvit.com/blog/devops-glossary-78-basic-devops-terms-in-simple-words/ [Accessed 13 Jul. 2023]'},
  {Number:'6',
    term: 'Continuous Deployment (CDE)',
  definition: 'Continuous deployment enables a development team to incorporate code segments into the production environment many times per day, giving a completely automated solution to continuous delivery.',
  sources: 'Plutora. (n.d.). DevOps DevOps Terminology: A Glossary. [online] Available at: https://www.plutora.com/devops-at-scale/terminology-glossary.'},
  {Number:'7',
    term: 'Exploratory Testing',
  definition: 'A conventional testing approach gives human testers the ability to explore and analyze potential problem areas that automated testing may not adequately capture, allowing them to identify flaws that would otherwise be ignored.',
  sources: 'Inc, Dz. (2017). 48 DevOps Terms You Should Know (A DevOps Glossary). [online] Medium. Available at: https://medium.com/@DZoneInc/48-devops-terms-you-should-know-a-devops-glossary-37e60fd23752 [Accessed 13 Jul. 2023].'},
  {Number:'8',
    term: 'Fail Fast',
  definition: 'In this technique, you give something a go, but if it doesnt work out, you quickly collect feedback, make improvements, and try again.',
  sources: 'Inc, Dz. (2017). 48 DevOps Terms You Should Know (A DevOps Glossary). [online] Medium. Available at: https://medium.com/@DZoneInc/48-devops-terms-you-should-know-a-devops-glossary-37e60fd23752 [Accessed 13 Jul. 2023].'},
  {Number:'9',
    term: 'Zabbix',
  definition: 'I recently discovered this fantastic open-source cloud infrastructure monitoring service. Its intended to monitor the status of various network resources and services. What I like best about it is that it includes a server as well as agents that collaborate to give smart alerting capabilities for distributed systems. Its as though you have your own attentive monitoring system watching over everything!',
  sources: 'Anon, (2018). DevOps glossary: 78 basic DevOps terms explained in simple words | IT Svit. [online] Available at: https://itsvit.com/blog/devops-glossary-78-basic-devops-terms-in-simple-words/ [Accessed 13 Jul. 2023]'},
  {Number:'10',
    term: 'Microservices',
  definition: 'The microservices architecture is a remarkable software development method that ideally combines with the service-oriented architecture (SOA). It beautifully organises an application into a magnificent collection of marvellously separate services. The fact that these services are extraordinarily fine-grained makes them even more nimble and versatile for designing new apps.',
  sources: 'www.globalknowledge.com. (n.d.). DevOps Glossary of Terms. [online] Available at: https://www.globalknowledge.com/ca-en/topics/devops/glossary-of-terms/ [Accessed 13 Jul. 2023].'},
  {
    Number:'11',
    term: 'Agent',
    definition: ' a simple framework that supports cross-functional self-organizing teams for incremental delivery and iterative development.',
    sources: 'Plutora. (n.d.). DevOps DevOps Terminology: A Glossary. [online] Available at: https://www.plutora.com/devops-at-scale/terminology-glossary.'},
    {Number:'12',
      term: 'Autonomy',
    definition: 'The ability to make decisions on ones own without consulting or deferring to those in positions of authority is referred to as autonomy.',
    sources: ' Plutora. (n.d.). DevOps DevOps Terminology: A Glossary. [online] Available at: https://www.plutora.com/devops-at-scale/terminology-glossary.', },
  {
    Number:'13',
    term: 'DevOps',
  definition: 'An organizational structure for IT where all teams, particularly operations and development teams, work together on both software development and deployment to boost software production agility and meet business objectives.  ',
  sources: 'Inc, Dz. (2017). 48 DevOps Terms You Should Know (A DevOps Glossary). [online] Medium. Available at: https://medium.com/@DZoneInc/48-devops-terms-you-should-know-a-devops-glossary-37e60fd23752.'},
  {Number:'14',
    term: 'Issue Tracking',
  definition: 'a procedure that enables programmers and quality control staff to follow the progression of new features and errors from identification to resolution.',
  sources: 'Inc, Dz. (2017). 48 DevOps Terms You Should Know (A DevOps Glossary). [online] Medium. Available at: https://medium.com/@DZoneInc/48-devops-terms-you-should-know-a-devops-glossary-37e60fd23752.'},
  {Number:'15',
    term: 'Canary Release',
  definition: 'The canary release works similarly and is derived from the phrase "canary in a coal mine". It is used to roll out a software version gradually to a limited subgroup of people so that it can be tested for security and functionality before being made available to the broader public.  ',
  sources: 'Plutora. (n.d.). DevOps DevOps Terminology: A Glossary. [online] Available at: https://www.plutora.com/devops-at-scale/terminology-glossary.'},
  {Number:'16',
    term: 'GitOps',
  definition: 'Using DevOps technologies and ideas, the GitOps framework automates infrastructure activities. Infrastructure and environment definitions can be managed using current tools with version control.  ',
  sources: 'octopus.com. (2022). DevOps glossary. [online] Available at: https://octopus.com/devops/glossary/ [Accessed 27 Jul. 2023].'},
  {Number:'17',
    term: 'Jenkins Pipeline',
  definition: 'Jenkins Pipeline is a collection of plugins that Jenkins suggests using when setting up a platform for continuous delivery.',
  sources: 'Inc, Dz. (2017). 48 DevOps Terms You Should Know (A DevOps Glossary). [online] Medium. Available at: https://medium.com/@DZoneInc/48-devops-terms-you-should-know-a-devops-glossary-37e60fd23752 [Accessed 13 Jul. 2023].'},
  {Number:'18',
    term: 'Mean Time to Recovery (MTTR)',
  definition: 'the typical amount of time it requires for a system or component to recover from a failure and resume normal operation.',
  sources: 'Inc, Dz. (2017). 48 DevOps Terms You Should Know (A DevOps Glossary). [online] Medium. Available at: https://medium.com/@DZoneInc/48-devops-terms-you-should-know-a-devops-glossary-37e60fd23752 [Accessed 13 Jul. 2023].'},
  {Number:'19',
    term: 'Pair Programming',
  definition: 'a method of developing software where two developers work on a feature rather than just one so that both developers may check the quality of the others code as it is being developed. ',
  sources: 'Anon, (2018). DevOps glossary: 78 basic DevOps terms explained in simple words | IT Svit. [online] Available at: https://itsvit.com/blog/devops-glossary-78-basic-devops-terms-in-simple-words/ [Accessed 13 Jul. 2023]'},
  {Number:'20',
    term: 'Rollback',
  definition: 'a process, either automatic or manual, that returns a database or program to a specific state.',
  sources: 'www.globalknowledge.com. (n.d.). DevOps Glossary of Terms. [online] Available at: https://www.globalknowledge.com/ca-en/topics/devops/glossary-of-terms/ [Accessed 13 Jul. 2023].'},
  {Number:'21',
  term: 'CI/CD (Continuous Integration/Continuous Delivery)',
definition: 'Continuous Integration/Continuous Delivery, or CI/CD, is a set of practises and principles that allow for frequent automated software releases. Continuous Integration entails automatically developing and testing code updates to assure integration and early detection of errors. Continuous Delivery focuses on automating the release and deployment procedures in order to deliver software to production environments reliably and often.',
sources: 'https://www.coursera.org/collections/devops-terms?utm_source=gg&utm_medium=sem&utm_campaign=B2C_APAC__Google_FTCOF_googlecerts_arte_PMax_Addtocart&utm_content=Degree&campaignid=20342757356&adgroupid=&device=c&keyword=&matchtype=&network=x&devicemodel=&adpostion=&creativeid=&hide_mobile_promo&gclid=CjwKCAjw5_GmBhBIEiwA5QSMxGRSfBatUFrgU9C3xnJen2DORxewbJV5wSrud5Km2nb2BO_XeJ8C5RoCecMQAvD_BwE'},
{Number:'22',
    term: 'Elasticity',
  definition: 'Elasticity in DevOps refers to the capacity to flexibly scale computing resources up or down based on demand. It entails employing cloud infrastructure or containerization technologies in real time to allocate and deallocate resources, assuring optimal performance and cost effectiveness in response to changing workloads.',
  sources: 'https://www.coursera.org/collections/devops-terms?utm_source=gg&utm_medium=sem&utm_campaign=B2C_APAC__Google_FTCOF_googlecerts_arte_PMax_Addtocart&utm_content=Degree&campaignid=20342757356&adgroupid=&device=c&keyword=&matchtype=&network=x&devicemodel=&adpostion=&creativeid=&hide_mobile_promo&gclid=CjwKCAjw5_GmBhBIEiwA5QSMxGRSfBatUFrgU9C3xnJen2DORxewbJV5wSrud5Km2nb2BO_XeJ8C5RoCecMQAvD_BwE'},
  {Number:'23',
    term: 'Jenkins',
  definition: 'Jenkins is a popular open-source automation server in DevOps for developing, testing, and delivering software applications. It offers a solid platform for continuous integration and delivery workflows, allowing teams to automate build processes, perform tests, and reliably release applications.',
  sources: 'www.globalknowledge.com. (n.d.). DevOps Glossary of Terms. [online] Available at: https://www.globalknowledge.com/ca-en/topics/devops/glossary-of-terms/ [Accessed 13 Jul. 2023].'},
  {Number:'24',
    term: 'Kubernetes',
  definition: 'Kubernetes is an open-source container orchestration technology that automates the deployment, scaling, and management of containerized applications.',
  sources: 'www.globalknowledge.com. (n.d.). DevOps Glossary of Terms. [online] Available at: https://www.globalknowledge.com/ca-en/topics/devops/glossary-of-terms/ [Accessed 13 Jul. 2023].'},
  {Number:'25',
    term: 'Orchestration',
  definition: 'DevOps orchestration is the automated coordination and management of numerous processes, services, and components to achieve a desired result. It entails establishing workflows, dependencies, and action sequences to ensure smooth execution and integration across various systems and processes.',
  sources: 'https://www.coursera.org/collections/devops-terms?utm_source=gg'},
  {Number:'26',
    term: 'Workflow',
  definition: 'In DevOps, a workflow refers to the tasks, activities, and stages taken to achieve a given outcome or deliver a software product. Workflows establish the sequence and dependencies of actions, ensuring that procedures are consistent and repeatable across the software development and delivery lifecycle',
  sources: 'https://www.coursera.org/collections/devops-terms?utm_source=gg'},
  {Number:'27',
    term: 'Build Agent',
  definition: 'A type of agent used in continuous integration that can be installed locally or remotely in relation to the continuous integration server. It sends and receives messages about handling software builds.',
  sources: 'Inc, Dz. (2017). 48 DevOps Terms You Should Know (A DevOps Glossary). [online] Medium. Available at: https://medium.com/@DZoneInc/48-devops-terms-you-should-know-a-devops-glossary-37e60fd23752.'},
  {Number:'28',
    term: 'Containers',
  definition: 'Resource isolation at the OS (rather than machine) level, typically in user space (in UNIX-based systems). Depending on the containerization technique, isolated elements may include a file system, disc quota, CPU and memory, I/O rate, root privileges, and network access.',
  sources: 'Plutora. (n.d.). DevOps DevOps Terminology: A Glossary. [online] Available at: https://www.plutora.com/devops-at-scale/terminology-glossary.'},
  {Number:'29',
    term: 'Exploratory Testing',
  definition: 'A manual testing technique in which human testers are free to test regions where they believe concerns may occur that automated testing will not detect.',
  sources: 'https://www.coursera.org/collections/devops-terms?utm_source=gg'},
  {Number:'30',
    term: 'Mean Time Between Failures (MTBF)',
  definition: 'A system or components reliability is measured by averaging the time between system failures.',
  sources: 'www.globalknowledge.com. (n.d.). DevOps Glossary of Terms. [online] Available at: https://www.globalknowledge.com/ca-en/topics/devops/glossary-of-terms/ [Accessed 13 Jul. 2023].'},
  {Number:'31',
    term: 'Terraform provider',
  definition: 'Terraform providers are typically linked to a particular infrastructure provider, which could be an IaaS provider (like AWS, GCP, Microsoft Azure, OpenStack), a PaaS provider (like Heroku), or a SaaS provider (like Terraform Cloud, DNSimple, or Cloudflare).',
  sources: 'Terraform Glossary | Terraform | HashiCorp Developer. (n.d.). Terraform Glossary | Terraform | HashiCorp Developer. [online] Available at: https://developer.hashicorp.com/terraform/docs/glossary#terraform-provider [Accessed 27 Aug. 2023]. '},
{Number:'32',
    term: 'Registry',
  definition: 'a collection of modules created by the Terraform community that can be forked and updated or utilised in their original form within a Terraform setup. You can find pre-made modules for the infrastructure components you need and examples of how to write Terraform in the registry, which can all help you get started with Terraform more quickly.',
  sources: 'www.globalknowledge.com. (n.d.). DevOps Glossary of Terms. [online] Available at: https://www.globalknowledge.com/ca-en/topics/devops/glossary-of-terms/ [Accessed 27 Aug. 2023].'},
{Number:'33',
    term: 'Resource Block',
  definition: 'If a matching real infrastructure item does not already exist, Terraform will build it during a run. If the existing object does not match the desired configuration, Terraform will modify the existing object. A resource block in a configuration tells Terraform to manage the described resource.',
  sources:'Terraform Glossary | Terraform | HashiCorp Developer. (n.d.). Terraform Glossary | Terraform | HashiCorp Developer. [online] Available at: https://developer.hashicorp.com/terraform/docs/glossary#terraform-provider [Accessed 27 Aug. 2023].  '},
{Number:'34',
    term: 'Root Module',
  definition: 'In contrast to child modules, which have their variables and outputs handled by the caller module, the root modules variables and outputs are handled directly by Terraform. Terraform Cloud,.tfvars files, CLI options, or environment variables can all be used to provide root variable values After a run root outputs are printed and kept in the state.',
  sources: 'Terraform Glossary | Terraform | HashiCorp Developer. (n.d.). Terraform Glossary | Terraform | HashiCorp Developer. [online] Available at: https://developer.hashicorp.com/terraform/docs/glossary#terraform-provider [Accessed 27 Aug. 2023].'},
{Number:'35',
    term: 'S3',
  definition: 'The "Simple Storage Service" by Amazon Web Services, which allows users to store and retrieve unrestricted data blobs.Many other self-hosted or cloud services offer S3-compatible APIs, allowing them to be utilised with software that was created to interact with S3.',
  sources: 'https://www.coursera.org/collections/devops-terms?utm_source=gg,'},
{Number:'36',
    term: 'SAML',
  definition: 'The SAML standard for authentication and authorisation is based on XML. With your internal SAML identity provider (IdP), Terraform Enterprise can serve as a service provider (SP) or relying party (RP).',
  sources: 'www.globalknowledge.com. (n.d.). DevOps Glossary of Terms. [online] Available at: https://www.globalknowledge.com/ca-en/topics/devops/glossary-of-terms/ [Accessed 13 Jul. 2023].'},
{Number:'37',
    term: 'Sentinel',
  definition: 'For handling policy as code, there is a language and runtime. enables you to specify guidelines for Terraform Cloud operations.',
  sources: 'Plutora. (n.d.). DevOps DevOps Terminology: A Glossary. [online] Available at: https://www.plutora.com/devops-at-scale/terminology-glossary.'},
{Number:'38',
    term: 'SSH Key',
  definition: 'a specific kind of server login credential based on public key cryptography.For two different types of operations, Terraform Cloud requires SSH private keys.',
  sources: 'Terraform Glossary | Terraform | HashiCorp Developer. (n.d.). Terraform Glossary | Terraform | HashiCorp Developer. [online] Available at: https://developer.hashicorp.com/terraform/docs/glossary#terraform-provider [Accessed 27 Aug. 2023].'},
{Number:'39',
    term: 'Terraform',
  definition: 'a device for effectively and safely creating, updating, and versioning infrastructure. Along with managing established and well-liked service providers, Terraform may also handle unique internal solutions.',
  sources: 'https://www.coursera.org/collections/devops-terms?utm_source=gg&utm_medium=sem&utm_campaign=B2C_APAC__Google_FTCOF_googlecerts_arte_PMax_Addtocart&utm_content=Degree&campaignid=20342757356&adgroupid=&device=c&keyword=&matchtype=&network=x&devicemodel=&adpostion=&creativeid=&hide_mobile_promo&gclid=CjwKCAjw5_GmBhBIEiwA5QSMxGRSfBatUFrgU9C3xnJen2DORxewbJV5wSrud5Km2nb2BO_XeJ8C5RoCecMQAvD_BwE'},
{Number:'40',
    term: 'Webhook',
  definition: 'a server-to-server HTTP request when one system sends data to another system in response to a change in its internal state.A webhooks recipient may respond to a request by returning data to the initiating system, by invoking further webhooks in response, by acting silently, or by completely ignoring the request.',
  sources: 'Terraform Glossary | Terraform | HashiCorp Developer. (n.d.). Terraform Glossary | Terraform | HashiCorp Developer. [online] Available at: https://developer.hashicorp.com/terraform/docs/glossary#terraform-provider [Accessed 27 Aug. 2023].'},
{Number:'41',
  term: 'Annotation',
definition: 'a key-value pair that can be used to tag objects with any non-identifying metadata.',
sources: 'www.globalknowledge.com. (n.d.). DevOps Glossary of Terms. [online] Available at: https://www.globalknowledge.com/ca-en/topics/devops/glossary-of-terms/ [Accessed 06 Sep. 2023].'},
{Number:'42',
  term: 'Cluster',
definition: 'a group of nodes, or worker computers, that execute containerized applications. There is at least one worker node in each cluster.',
sources: 'Kubernetes. (n.d.). Glossary. [online] Available at: https://kubernetes.io/docs/reference/glossary/?fundamental=true.'},
{Number:'43',
    term: 'Container Environment Variables',
  definition: 'Environment variables for containers are name=value pairs that offer helpful data to containers running in a pod.',
  sources: 'Kubernetes. (n.d.). Glossary. [online] Available at: https://kubernetes.io/docs/reference/glossary/?fundamental=true.'},
  {Number:'44',
  term: 'Disruption',
definition: 'Events known as disruptions cause one or more Pods to become unusable. A disruption has an impact on workload resources that rely on the affected Pods, such as Deployment.',
sources: 'Inc, Dz. (2017). 48 DevOps Terms You Should Know (A DevOps Glossary). [online] Medium. Available at: https://medium.com/@DZoneInc/48-devops-terms-you-should-know-a-devops-glossary-37e60fd23752.'},
{Number:'45',
    term: 'Init Container',
  definition: 'A container or containers for initialisation that must run completely before any containers for application do.',
  sources: 'Anon, (2018). DevOps glossary: 78 basic DevOps terms explained in simple words | IT Svit. [online] Available at: https://itsvit.com/blog/devops-glossary-78-basic-devops-terms-in-simple-words/ [Accessed 13 Jul. 2023].'},
  {Number:'46',
  term: 'RBAC (Role-Based Access Control)',
definition: 'manages authorisation decisions, allowing administrators to use the Kubernetes API to dynamically configure access policies.',
sources: 'www.globalknowledge.com. (n.d.). DevOps Glossary of Terms. [online] Available at: https://www.globalknowledge.com/ca-en/topics/devops/glossary-of-terms/ [Accessed 06 Sep. 2023].'},
{Number:'47',
    term: 'Toleration',
  definition: 'a fundamental object with the three necessary attributes of key, value, and effect. Pods can be scheduled on nodes or node groups with matching taints thanks to tolerances.',
sources: 'Kubernetes. (n.d.). Glossary. [online] Available at: https://kubernetes.io/docs/reference/glossary/?fundamental=true.'},
{Number:'48',
    term: 'kubelet',
  definition: 'an agent that is installed on each cluster node. It confirms that containers are operating within a Pod.',
  sources: 'Anon, (2018). DevOps glossary: 78 basic DevOps terms explained in simple words | IT Svit. [online] Available at: https://itsvit.com/blog/devops-glossary-78-basic-devops-terms-in-simple-words/ [Accessed 13 Jul. 2023].'},
  {Number:'49',
  term: 'kOps (Kubernetes Operations)',
definition: 'A production-grade, highly available Kubernetes cluster may be built, destroyed, upgraded, and maintained with the assistance of kOps, which will also set up the required cloud infrastructure.',
sources: 'Kubernetes. (n.d.). Glossary. [online] Available at: https://kubernetes.io/docs/reference/glossary/?fundamental=true.'},
{Number:'50',
    term: 'QoS Class',
  definition: 'Kubernetes can categorise Pods in the cluster into different classes and decide how to schedule and evict them using QoS Class (Quality of Service Class).',
  sources: 'www.globalknowledge.com. (n.d.). DevOps Glossary of Terms. [online] Available at: https://www.globalknowledge.com/ca-en/topics/devops/glossary-of-terms/ [Accessed 06 Sep. 2023].'},
  // Add more glossary terms here
];
/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { glossary: glossary });
});

module.exports = router;
